<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terminplanungs-System</title>
  <style>
    /* CSS-Stile */
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
    }
    .login-container, .booking-container, .table-container {
      max-width: 800px;
      margin: 20px auto;
      padding: 20px;
      border: 1px solid #ccc;
      border-radius: 5px;
    }
    .form-group {
      margin-bottom: 15px;
    }
    .form-group label {
      display: block;
      margin-bottom: 5px;
    }
    .form-group input, .form-group button, .form-group select {
      width: 100%;
      padding: 8px;
      border: 1px solid #ccc;
      border-radius: 3px;
    }
    .form-group button {
      background-color: #007bff;
      color: #fff;
      cursor: pointer;
    }
    .form-group button:hover {
      background-color: #0056b3;
    }
    /* Stile für die Tabelle */
    table {
      width: 100%;
      border-collapse: collapse;
    }
    table, th, td {
      border: 1px solid #ccc;
    }
    th, td {
      padding: 8px;
      text-align: left;
    }

    /* Animationen */
    @keyframes fadeIn {
      from {
        opacity: 0;
      }
      to {
        opacity: 1;
      }
    }
  </style>
</head>
<body>

<!-- Anmelde-Seite -->
<div class="login-container">
  <h1>Anmeldung</h1>
  <div class="form-group">
    <label for="username">Benutzername:</label>
    <input type="text" id="username">
  </div>
  <div class="form-group">
    <label for="password">Passwort:</label>
    <input type="password" id="password">
  </div>
  <div class="form-group">
    <button id="loginButton">Einloggen</button>
  </div>
</div>

<!-- Termin buchen Seite -->
<div class="booking-container" style="display: none;">
  <h1>Termin buchen</h1>
  <div class="form-group">
    <label for="date">Datum:</label>
    <input type="date" id="date">
  </div>
  <div class="form-group">
    <label for="time">Uhrzeit:</label>
    <input type="time" id="time">
  </div>
  <div class="form-group">
    <label for="reason">Grund des Termins:</label>
    <select id="reason">
      <option value="Einkaufen">Einkaufen</option>
      <option value="Einfach nur Reden">Einfach nur Reden</option>
      <option value="Sonstiges">Sonstiges</option>
      <option value="Private Gespräche">Private Gespräche</option>
    </select>
  </div>
  <div class="form-group">
    <button id="bookButton">Termin buchen</button>
    <button id="logoutButton">Abmelden</button>
  </div>
</div>

<!-- Tabelle für Buchungen -->
<div class="table-container" style="display: none;">
  <h1>Buchungen</h1>
  <table id="bookingTable">
    <thead>
      <tr>
        <th>Datum</th>
        <th>Uhrzeit</th>
        <th>Grund</th>
        <th>Aktion</th>
      </tr>
    </thead>
    <tbody>
      <!-- Hier werden die Buchungen eingefügt -->
    </tbody>
  </table>
</div>

<!-- JavaScript -->
<script>
  // Event Listener für den Login-Button
  document.getElementById('loginButton').addEventListener('click', function() {
    const username = document.getElementById('username').value;
    const password = document.getElementById('password').value;

    // Dummy-Benutzerdaten (normalerweise würden diese in einer sicheren Datenbank gespeichert werden)
    const users = [
      { username: '123', password: '123' }
    ];

    const user = users.find(u => u.username === username);

    if (user && user.password === password) {
      alert('Anmeldung erfolgreich!');
      // Anzeige der Terminbuchungsseite
      document.querySelector('.login-container').style.display = 'none';
      document.querySelector('.booking-container').style.display = 'block';
      document.querySelector('.table-container').style.display = 'block';
      // Daten aus dem lokalen Speicher laden und in die Tabelle einfügen
      loadBookings();
    } else {
      alert('Ungültige Anmeldeinformationen.');
    }
  });

  // Funktion zum Hinzufügen einer Buchung zur Tabelle und zum Speichern im lokalen Speicher
  function addBooking(date, time, reason) {
    const tableBody = document.querySelector('#bookingTable tbody');
    const newRow = tableBody.insertRow();
    const dateCell = newRow.insertCell(0);
    const timeCell = newRow.insertCell(1);
    const reasonCell = newRow.insertCell(2);
    const actionCell = newRow.insertCell(3);

    dateCell.textContent = date;
    timeCell.textContent = time;
    reasonCell.textContent = reason;
    actionCell.innerHTML = '<button class="cancelButton">Stornieren</button>';

    // Event Listener für den Stornierungs-Button
    actionCell.querySelector('.cancelButton').addEventListener('click', function() {
      // Stornierung mit Animation
      newRow.style.animation = 'fadeOut 0.5s forwards';

      setTimeout(function() {
        tableBody.removeChild(newRow);
        // Buchung aus dem lokalen Speicher entfernen
        removeBookingFromLocalStorage(newRow.rowIndex - 1);
      }, 500);
    });

    // Speichern der Buchung im lokalen Speicher
    const bookings = JSON.parse(localStorage.getItem('bookings')) || [];
    const booking = { date, time, reason };
    bookings.push(booking);
    localStorage.setItem('bookings', JSON.stringify(bookings));

    // Animation für den neuen Eintrag
    newRow.style.opacity = 0;
    newRow.style.animation = 'fadeIn 1s forwards';
  }

  // Funktion zum Laden der Buchungen aus dem lokalen Speicher
  function loadBookings() {
    const bookings = JSON.parse(localStorage.getItem('bookings')) || [];
    bookings.forEach(booking => {
      addBooking(booking.date, booking.time, booking.reason);
    });
  }

  // Funktion zum Entfernen einer Buchung aus dem lokalen Speicher
  function removeBookingFromLocalStorage(index) {
    const bookings = JSON.parse(localStorage.getItem('bookings')) || [];
    bookings.splice(index, 1);
    localStorage.setItem('bookings', JSON.stringify(bookings));
  }

  // Event Listener für den Buchen-Button
  document.getElementById('bookButton').addEventListener('click', function() {
    const date = document.getElementById('date').value;
    const time = document.getElementById('time').value;
    const reason = document.getElementById('reason').value;

    // Überprüfen, ob Datum und Uhrzeit eingegeben wurden
    if (date && time) {
      addBooking(date, time, reason);
      alert('Termin erfolgreich gebucht!');
    } else {
      alert('Bitte geben Sie Datum und Uhrzeit ein.');
    }
  });

  // Event Listener für den Abmelden-Button
  document.getElementById('logoutButton').addEventListener('click', function() {
    // Bestätigungsnachricht und Weiterleitung zur Anmeldeseite
    if (confirm('Möchten Sie sich wirklich abmelden?')) {
      localStorage.removeItem('bookings');
      location.href = 'index.html'; // Zur Anmeldeseite weiterleiten
    }
  });
</script>

</body>
</html>
